services:
  go-correios-sync:
    container_name: go-correios-sync
    build: .
    network_mode: host
    user: "${UID}:${GID}"
    volumes:
      - ./converted_files:/go/converted_files:ro
      - ./database:/go/database:rw
  postgres:
    container_name: postgres
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
